# Generated by Django 4.2.11 on 2024-04-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValidEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('submission_time', models.TimeField(auto_now_add=True)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
