# Generated by Django 5.0.1 on 2024-03-23 06:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0006_alter_validemail_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='validemail',
            name='submission_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
